In [4]:
import pandas as pd
from sgt.utils_wren import get_aflow_label_from_spg_analyzer,get_aflow_label_from_spglib

In [7]:
df = pd.read_json('./pretrain_data/norm_combined.json')
df

,formula,spg_symbol,a,b,c,alpha,beta,gama
0,Ca2 Mn2 Si2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
1,Rb2 Mn2 P2,P4/n2_1/m2/m,-1.044325,-1.061562,2.038929,0.042241,-0.163288,0.135576
2,Tm1 Co2 B2 C1,I4/m2/m2/m,-1.110382,-1.115604,-0.977559,1.171639,0.842580,0.135576
3,Tm2 Co4 B4 C2,I4/m2/m2/m,-1.109779,-1.115111,-0.378723,0.042241,-0.163288,0.135576
4,Tm2 Co4 B4 C2,P4mm,-1.109779,-1.115111,-0.378723,0.042241,-0.163288,0.135576
...,...,...,...,...,...,...,...,...
642454,Zn4 H74 C68 O26,P1,1.427002,0.960234,0.605300,0.043190,-0.161175,0.136650
642455,Cu2 H28 C24 N14 O8,P1,0.009451,-0.020553,-0.306398,-0.303958,-0.308771,-0.348853
642456,Zn2 H13 C53 N17 O8,P1,0.055615,-0.037962,-0.346761,-0.310016,-0.163293,0.135520
642457,Zn12 H72 C120 O48,P1,2.570421,1.895790,1.268685,-1.880771,-1.875921,-1.405885
642458,Zn2 H40 C43 N2 O19,P1,0.860844,0.497671,0.208941,0.041812,-0.254546,0.135509

In [9]:
import json
with open('./sgt/spg_dict.json','r') as file:
    dict = json.load(file)

In [17]:
max = 0
for keys,values in dict.items():
    if max < len(values):
        max = len(values)
max
    # break

12

In [8]:
max_e = 0
for x in df['formula']:
    n_elements = len(x.split(' '))
    if max_e < n_elements:
        max_e = n_elements
max_e

20

In [5]:
from sgt.utils_my import get_spg_tokens

In [6]:
get_spg_tokens('P1')

['P1',
 'spg_1',
 '1.0',
 '1',
 'triclinic',
 '-1',
 'Enantiomorphic',
 'non_polar',
 'P',
 '1',
 '1',
 '1']

In [ ]:
get_aflow_label_from_spglib()

In [ ]:
get_aflow_label_from_spg_analyzer()

In [ ]:
df = pd.read_csv('./data/mp.csv')
df

In [20]:
df = pd.read_json('./pretrain_data/norm_combined.json')
df

,formula,spg_symbol,a,b,c,alpha,beta,gama
0,Ca2 Mn2 Si2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
1,Rb2 Mn2 P2,P4/n2_1/m2/m,-1.044325,-1.061562,2.038929,0.042241,-0.163288,0.135576
2,Tm1 Co2 B2 C1,I4/m2/m2/m,-1.110382,-1.115604,-0.977559,1.171639,0.842580,0.135576
3,Tm2 Co4 B4 C2,I4/m2/m2/m,-1.109779,-1.115111,-0.378723,0.042241,-0.163288,0.135576
4,Tm2 Co4 B4 C2,P4mm,-1.109779,-1.115111,-0.378723,0.042241,-0.163288,0.135576
...,...,...,...,...,...,...,...,...
642454,Zn4 H74 C68 O26,P1,1.427002,0.960234,0.605300,0.043190,-0.161175,0.136650
642455,Cu2 H28 C24 N14 O8,P1,0.009451,-0.020553,-0.306398,-0.303958,-0.308771,-0.348853
642456,Zn2 H13 C53 N17 O8,P1,0.055615,-0.037962,-0.346761,-0.310016,-0.163293,0.135520
642457,Zn12 H72 C120 O48,P1,2.570421,1.895790,1.268685,-1.880771,-1.875921,-1.405885
642458,Zn2 H40 C43 N2 O19,P1,0.860844,0.497671,0.208941,0.041812,-0.254546,0.135509

In [25]:
new_df=pd.DataFrame({})
new_df

Empty DataFrame
Columns: []
Index: []

In [33]:
new_df = df.iloc[:0]
new_df

Empty DataFrame
Columns: [formula, spg_symbol, a, b, c, alpha, beta, gama]
Index: []

In [37]:
import itertools
new_df = df.iloc[:0]
for idx in range(len(df)):
    elements = df['formula'][idx].split(' ')
    # print(elements)
    permutations = list(itertools.permutations(elements))

    for p in permutations:
        new_formula = (' '.join(p))
        new_row = df.iloc[idx:idx+1,1:]
        new_row['formula'] = new_formula
        new_df = pd.concat([new_df,new_row])
    # break
new_df

:

:

In [ ]:
new_df.to_csv('./pretrain_data/augmen.csv',index=None)

,formula,spg_symbol,a,b,c,alpha,beta,gama
0,Ca2 Mn2 Si2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
0,Ca2 Si2 Mn2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
0,Mn2 Ca2 Si2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
0,Mn2 Si2 Ca2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
0,Si2 Ca2 Mn2,P4/n2_1/m2/m,-1.040198,-1.058186,1.850505,0.042241,-0.163288,0.135576
...,...,...,...,...,...,...,...,...
16455,S2 C2 Mn2 O14 Na4,P12_1/m1,-0.772796,-0.599206,-0.549101,0.042241,-0.148912,0.135576
16455,S2 C2 O14 Na4 Mn2,P12_1/m1,-0.772796,-0.599206,-0.549101,0.042241,-0.148912,0.135576
16455,S2 C2 O14 Mn2 Na4,P12_1/m1,-0.772796,-0.599206,-0.549101,0.042241,-0.148912,0.135576
16455,S2 O14 Na4 Mn2 C2,P12_1/m1,-0.772796,-0.599206,-0.549101,0.042241,-0.148912,0.135576
16455,S2 O14 Na4 C2 Mn2,P12_1/m1,-0.772796,-0.599206,-0.549101,0.042241,-0.148912,0.135576

In [18]:
from pymatgen.core import Composition
Composition(new_formula).formula

'Ca2 Mn2 Si2'

In [ ]:
import torch
position_id = torch.cat([torch.arange(2,130+1),-1*torch.ones(20).type(torch.int)])
position_id

In [ ]:
position_id.shape

In [ ]:
wbm = pd.read_csv('./data/wbm.csv')
wbm